<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLEBOklA\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLEBOklA/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerLEBOklA.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerLEBOklA\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerLEBOklA\appAppKernelProdContainer([
    'container.build_hash' => 'LEBOklA',
    'container.build_id' => '4504ce27',
    'container.build_time' => 1724931470,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLEBOklA');
