<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq2f9Y814I1IrE53m6j32'."\n".'IUSldcbu9Mwtes5ZEWy0HYo6qDZKcOVtVewqcGTQUNR4rfL+LAWS2jQyJZOxuh/B'."\n".'ewhWT6TTnlm2xVQG9D4vvvFPCQ75wlzFGy2bfQfvbzKRE0g32am2w56lyweV4MpO'."\n".'Hx87PVqllA7RdphRz2ZbmruD2Ko2BL9rMOmGuZ/Al8YYRkX0Pb2laCdyKKgg4o5g'."\n".'/dt8xankHN9K9Jj9UVZalQOsSJTDukDz4zdGROICAexTprAYDwBHCQFdRValVlIk'."\n".'QbKegaLNDpDaw5fJ09JQmZgazwGXED05IJLDmUtk4ALl6K/tgGFLSZA2rLDKxCXg'."\n".'1QIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
