<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLKsUkQ1\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLKsUkQ1/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLKsUkQ1.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLKsUkQ1\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerLKsUkQ1\appAppKernelDevDebugContainer([
    'container.build_hash' => 'LKsUkQ1',
    'container.build_id' => '1a3b4d58',
    'container.build_time' => 1724971978,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLKsUkQ1');
